spring:
  application:
    name: department-service
  datasource:
    url: jdbc:postgresql://localhost:5432/department_db
    username: postgres
    password: ZOV
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    com.company.department: DEBUG 